apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: golden-container
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: golden-container
    app.kubernetes.io/part-of: golden-container
  name: golden-container
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: golden-container
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: golden-container
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/zregvart-tenant/golden-container/golden-container@sha256:a7a1afc12ecc191a86ff9313909b4cbd83647928157423a0b78493558596d9d1
        imagePullPolicy: Always
        name: container-image
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
