apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: golden-container
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: golden-container
    app.kubernetes.io/part-of: golden-container
  name: golden-container
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: golden-container
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: golden-container
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/zregvart-tenant/golden-container/golden-container@sha256:866b55533b166bb0df7a9747c1a8177aaeac51e8e5fe5d89cfb7129dd2281272
        imagePullPolicy: Always
        name: container-image
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
